In [1]:
import warnings

In [2]:
warnings.simplefilter('ignore')

In [4]:
os.chdir('/Users/bdemeo/Documents/bergerlab/lsh/ample/bin')
from hashers import *

In [3]:
from datatools import *
from dataset import *
import matplotlib.pyplot as plt
import ipywidgets as widgets
import os
import csv
from ipywidgets import interact, interact_manual
from sklearn.preprocessing import LabelEncoder

In [5]:
plt.rcParams['figure.figsize'] = [10, 10]

In [6]:
os.chdir('/Users/bdemeo/Documents/bergerlab/lsh/ample')

In [7]:
pbmc = open_data('pbmc', dimred=True,annos=['labels'])


In [8]:
pbmc.subsamples['ft']

<dataset.dataset instance at 0x117aad1b8>

In [9]:
pbmc.annos

{'labels': ['CD4+_T_Helper2',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD56+_NK',
  'CD14+_Monocyte',
  'CD56+_NK',
  'CD56+_NK',
  'CD4+/CD45RA+/CD25-_Naive_T',
  'CD4+_T_Helper2',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD4+_T_Helper2',
  'CD56+_NK',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD56+_NK',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD4+_T_Helper2',
  'CD4+/CD45RA+/CD25-_Naive_T',
  'CD4+_T_Helper2',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD8+_Cytotoxic_T',
  'CD4+_T_Helper2',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD4+/CD45RO+_Memory',
  'CD56+_NK',
  'CD56+_NK',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD4+_T_Helper2',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD56+_NK',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD4+_T_Helper2',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD56+_NK',
  'CD4+/CD45RA+/CD25-_Naive_T',
  'CD56+_NK',
  'CD4+_T_Helper2

In [10]:
pbmc.subsamples['ft'].annos

{'labels': ['CD19+_B',
  'CD4+/CD45RO+_Memory',
  'Dendritic',
  'CD56+_NK',
  'CD19+_B',
  'CD4+_T_Helper2',
  'CD56+_NK',
  'CD14+_Monocyte',
  'CD19+_B',
  'CD19+_B',
  'CD56+_NK',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD56+_NK',
  'CD4+_T_Helper2',
  'CD8+_Cytotoxic_T',
  'CD8+_Cytotoxic_T',
  'CD8+_Cytotoxic_T',
  'CD19+_B',
  'CD4+/CD45RO+_Memory',
  'CD14+_Monocyte',
  'CD4+/CD45RA+/CD25-_Naive_T',
  'CD4+/CD45RO+_Memory',
  'CD19+_B',
  'CD19+_B',
  'CD8+_Cytotoxic_T',
  'Dendritic',
  'CD19+_B',
  'CD19+_B',
  'CD4+/CD45RO+_Memory',
  'CD56+_NK',
  'CD56+_NK',
  'CD8+_Cytotoxic_T',
  'CD4+/CD45RO+_Memory',
  'CD19+_B',
  'CD56+_NK',
  'CD19+_B',
  'CD56+_NK',
  'CD56+_NK',
  'CD4+/CD45RA+/CD25-_Naive_T',
  'CD14+_Monocyte',
  'CD8+_Cytotoxic_T',
  'CD4+/CD45RO+_Memory',
  'CD19+_B',
  'CD19+_B',
  'CD19+_B',
  'CD4+/CD45RO+_Memory',
  'CD8+_Cytotoxic_T',
  'CD19+_B',
  'CD8+_Cytotoxic_T',
  'CD8+_Cytotoxic_T',
  'CD56+_NK',
  'CD8+/CD45RA+_Naive_Cytotoxic',
  'CD4+_T_Helper2',


In [12]:
pbmc.grow_all()

aW50ZXJhY3RpdmUoY2hpbGRyZW49KERyb3Bkb3duKGRlc2NyaXB0aW9uPXUnc2FtcGxlJywgb3B0aW9ucz0oJ2Z0JywpLCB2YWx1ZT0nZnQnKSwgT3V0cHV0KCkpLCBfZG9tX2NsYXNzZXM9KHXigKY=


In [9]:
zheng = open_data('zheng', dimred=True, annos=['labels', 'patients'])
zheng.make_subsample(downsampler=uniformSampler(zheng.data),max_size=1000, name='unif')
zheng.make_subsample(downsampler=PCALSH(zheng.data,gridSize=0.1),max_size=1000,name='PCA')

downsampling with grid size 96.5010932554
96.50109325543224
[[53.]
 [53.]
 [53.]
 ...
 [61.]
 [61.]
 [53.]]
starting sampling
sampled 83 out of auto before reset
finished downsampling
sampled 83
2019-07-08 12:11:40.571638 | Grid size 83, decrease unit to 48.2505466277
downsampling with grid size 48.2505466277
48.25054662771612
[[ 907.]
 [ 907.]
 [1285.]
 ...
 [3128.]
 [ 652.]
 [1378.]]
starting sampling
sampled 3515 out of auto before reset
finished downsampling
sampled 3515
2019-07-08 12:11:43.003572 | Grid size 3515, increase scale to 72.3758199416
downsampling with grid size 72.3758199416
72.37581994157418
[[ 12.]
 [ 12.]
 [455.]
 ...
 [300.]
 [300.]
 [ 12.]]
starting sampling
sampled 507 out of auto before reset
finished downsampling
sampled 507
2019-07-08 12:11:44.528125 | Grid size 507, decrease unit to 60.3131832846
downsampling with grid size 60.3131832846
60.31318328464515
[[1285.]
 [ 981.]
 [1265.]
 ...
 [ 470.]
 [ 648.]
 [ 796.]]
starting sampling
sampled 1615 out of auto be

In [19]:
zheng.grow_all()

aW50ZXJhY3RpdmUoY2hpbGRyZW49KERyb3Bkb3duKGRlc2NyaXB0aW9uPXUnc2FtcGxlJywgb3B0aW9ucz0oJ1BDQScsICd1bmlmJyksIHZhbHVlPSdQQ0EnKSwgT3V0cHV0KCkpLCBfZG9tX2PigKY=


In [9]:
zheng.grow_all()

aW50ZXJhY3RpdmUoY2hpbGRyZW49KERyb3Bkb3duKGRlc2NyaXB0aW9uPXUnc2FtcGxlJywgb3B0aW9ucz0oJ3VuaWYnLCksIHZhbHVlPSd1bmlmJyksIE91dHB1dCgpKSwgX2RvbV9jbGFzc2XigKY=


In [8]:
print(zheng.data.shape)

(4070, 100)


In [35]:
for p in np.unique(zheng.annos['patients']):
    zheng.subsamples[p] = [x for x in range(zheng.numObs) if zheng.annos['patients'][x] == p]

In [8]:
zheng.make_embedding(max_size=20000)

In [8]:
grow(zheng)

NameError: name 'grow' is not defined

In [40]:
def grow(data, subsets = None, color=None):
    
    
    if subsets is None:
        subsets = data.subsets.keys()
    
    if color is None:
        color = data.annos.keys()
    
    max_n = max([e.shape[0] for e in [data.embeddings[name] for name in embedding_types]])
    print(max_n)
    
    @interact
    def build_plot(N=(1,max_n,1), method = embedding_types, color=color):
        if color is None:
            colors = [1]*data.numObs
        else:
            le = LabelEncoder().fit(data.annos[color])
            colors = le.transform(data.annos[color])
        
        numPts = min([N, data.embeddings[method].shape[0]])
        
        plt.scatter(data.embeddings[method][:N,0], 
                    data.embeddings[method][:N,1],
                    label = [data.annos[color][i] for i in data.subsamples[method][:N]],
                   c=[colors[i] for i in data.subsamples[method][:N]],
                   cmap='Set1')
        plt.legend()
            
    

In [15]:
reload(dataset)

ImportError: No module named dataset